### ISSUE TITLE
[BUG] cannot call [scheduleAlarm/ sendNotification] multiple times

### ISSUE THREAD

**Issue by Cody2333** [emekalites/react-native-alarm-notification#1]
When I try to call scheduleAlarm or sendNotification multiple times like this:
```
const notificationTpl = {
  // id: '123',
  title: "title",               // Required 
  message: "message",           // Required 
  auto_cancel: false,                            // default: true 
  vibrate: true,                                      
  vibration: 100,                               // default: 100, no vibration if vibrate: false 
  small_icon: "ic_launcher",                    // Required 
  large_icon: "ic_launcher",                          
  play_sound: true,                                    
  sound_name: null,                             // Plays custom notification ringtone if sound_name: null 
  color: "red",                                       
  // schedule_once: true,                          // Works with ReactNativeAN.scheduleAlarm so alarm fires once 
}
ReactNativeAN.sendNotification(notificationTpl)
ReactNativeAN.sendNotification(notificationTpl) 
```
Got an Error:
You attempted to set the key `id` with the value `"1503550784856"` on an object that is meant to be immutable and has been frozen.

**Comment by kingctan** [comment]
how to fix this problem? I also meet it.
Thanks.

**Comment by emekalites** [comment]
fixed in 1.0.7

Please note that you always have to set **id** in notificationTpl object

`const notificationTpl = {
  // id: '123',
  title: "title",               // Required 
  message: "message",           // Required 
  auto_cancel: false,                            // default: true 
  vibrate: true,                                      
  vibration: 100,                               // default: 100, no vibration if vibrate: false 
  small_icon: "ic_launcher",                    // Required 
  large_icon: "ic_launcher",                          
  play_sound: true,                                    
  sound_name: null,                             // Plays custom notification ringtone if sound_name: null 
  color: "red",                                       
  // schedule_once: true,                          // Works with ReactNativeAN.scheduleAlarm so alarm fires once 
}

notif1.id = '1234';
ReactNativeAN.sendNotification(notif1);

notif2.id = '5678';
ReactNativeAN.sendNotification(notif2) `

**Comment by emekalites** [comment]
@Cody2333 @kingctan please try out the fix.

**Comment by kingctan** [comment]
also the same error.

maybe const object can't be changed.
and I tried the var, it don't work.

**Comment by kingctan** [comment]
add ReactNativeAN.removeAllFiredNotifications()  fixed above problem.

**Comment by Cody2333** [comment]
```
import _ from 'lodash';

// first time calling sendNotification, it works
Object.assign(notificationTpl , {id: '1111'})
ReactNativeAN.sendNotification(notificationTpl)

//Got an Error:
//You attempted to set the key id with the value "1503550784856" on an object that is meant to be // 
//immutable and has been frozen.
const newTpl = Object.assign(notificationTpl , {id: '1223'})
ReactNativeAN.sendNotification(newTpl)

// solution: clone a new object in some way
const anotherTpl= _.cloneDeep(newTpl)
ReactNativeAN.sendNotification(anotherTpl)
```

**Comment by emekalites** [comment]
I'll look more into this, meanwhile remove all fired notifications before sending another concurrent notification. There should be a more elegant way to set multiple notifications.

**Comment by emekalites** [comment]
I think this should work in the current version. v1.1.0. Reopen if any issues with this bug comes up. Thanks.
