### ISSUE TITLE
Why substract one month on Alarm fire date ?

### ISSUE THREAD

**Issue by Lolinpiko** [emekalites/react-native-alarm-notification#50]
Why would you want to substract one month in `calendar.set(Calendar.MONTH, alarm.getMonth() - 1);` and repeat this action multiple times ?

This action is in ANModule (l. 105) and three times in AlarmUtils (l. 137, 179, 188).

**Comment by emekalites** [comment]
when setting a Month in `GregorianCalendar()`, you need to subtract the actual month by 1 because the GregorianCalendar class starts counting Month from 0.
Regarding the repetition in AlarmUtils, you'll notice i needed to set the calendar with the date and time from the model so i can get `calendar.getTimeInMillis()` to set the alarm. 

I'll add comments and probably refactor (remove unnecessary repetitions) in the next release.

**Comment by emekalites** [comment]
In ANModule, you'll realize i did the opposite, I added 1 month to the Month i got from GregorianCalendar class in `alarm.setMonth(calendar.get(Calendar.MONTH) + 1);` and thats because if you're counting from 0, the month will be 1 less than the actual month.

**Comment by Lolinpiko** [comment]
This is weird because I removed all `-1` and `+1` references and notifications are scheduled fine

**Comment by emekalites** [comment]
It worked for you because in ANModule.java Line 98 below, the GregorianCalendar class has already been set. so if you remove the -1 and +1, the date wont be wrong in the GregorianCalendar class but if you log the alarm model, you'll realize the month is always minus 1 of the actual month.
```
SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss", Locale.ENGLISH);
Calendar calendar = new GregorianCalendar();
calendar.setTime(sdf.parse(datetime));
```

you could check [https://stackoverflow.com/questions/27434488/gregorian-calendar-month-of-year](https://stackoverflow.com/questions/27434488/gregorian-calendar-month-of-year) or check this docs [https://docs.oracle.com/javase/8/docs/api/constant-values.html#java.util.Calendar.JANUARY](https://docs.oracle.com/javase/8/docs/api/constant-values.html#java.util.Calendar.JANUARY)
