### ISSUE TITLE
keeps ringing when App is close

### ISSUE THREAD

**Issue by Zeroxys** [emekalites/react-native-alarm-notification#82]
Hello @emekalites  thanks for this amazing package you save my life :)
I encounter a issue when the app is closed : 

When the app is running in the background (minimized) and I swipe the message it stops ringing.

When The app is completely closed however, I receive the alarm, the phone starts ringing but it continues ringing after I swip the message away. Only solution is to open the app and close it completely otherwise the phone continues ringing.

otherwise if I press the notification and the app is completely closed this listener never fired it

```
DeviceEventEmitter.addListener("OnNotificationOpened", async function (e) {
        console.log(e)      
});

```
I'm doing something wrong ?

**Comment by emekalites** [comment]
Hi @Zeroxys 
I would like to know if you updated your `AndroidManifest.xml`. The plugin is designed to stop alarm from ringing after dismissing the notification.

**Comment by laurent22** [comment]
@Zeroxys, did you find a fix for this? Several users of my apps have also reported this issue (for example [here](https://github.com/laurent22/joplin/issues/4086)). My `AndroidManifest.xml` is the same as in the doc. Any idea what could be the issue?

**Comment by laurent22** [comment]
@emekalites, I can replicate this bug consistently on emulator too using this steps:

- Setup a new alarm
- Completely close the application
- The alarm rings
- Press on the notification
- The app opens, but the alarms keep ringing and no way to stop it
- Close the app completely again
- The alarm finally stops

My AndroidManifest.xml is exactly as described in the installation section. Do you know by any chance what might be the issue? Is there perhaps some code that should also be added to MainApplication.java to make the alarm stop?

For reference, this is the bug report from one of our users: https://github.com/laurent22/joplin/issues/4086

**Comment by nguyenxuankiet262** [comment]
I have same issue. I think the issue was caused when you press on the notification but don't press dismiss button

**Comment by laurent22** [comment]
still a major issue

**Comment by vishva-shukla** [comment]
I'm facing the same issue any solution?

**Comment by easiestripes** [comment]
any updates on this? because this is still a big problem for users

**Comment by roman-r-m** [comment]
The problem is here:
https://github.com/emekalites/react-native-alarm-notification/blob/a1d30361db60a82b97279a583540f4f08cf4948a/android/src/main/java/com/emekalites/react/alarm/notification/AlarmDismissReceiver.java#L15

If the app is not running there's no react context so the alarm is not cancelled because there's no `else` for this `if`

@emekalites are you accepting pull requests? I can fix this and 2 or 3 other issues I've found,

**Comment by MohammedMaaz** [comment]
Hi @roman-r-m 
Were you able to fix this issue by modifying the above code accordingly?

**Comment by roman-r-m** [comment]
Well, I ended up rewriting a significant part of Android code because there were several bugs in there, not just this one.
I'm not going to bother submitting a PR as this repo seems abandoned and my PR will be closed by the bot.

The code is here: https://github.com/roman-r-m/joplin-rn-alarm-notification

Note that I have only looked at functions that are needed to the app I'm working on (Joplin), some parts of the code aren't tested and may not work properly.

**Comment by MohammedMaaz** [comment]
Thanks for this @roman-r-m

**Comment by roman-r-m** [comment]
Just to be clear - I am not going to support this package for general usage, so if you decide to use it, be aware of this.

**Comment by MohammedMaaz** [comment]
No problem. Thanks for informing though.

**Comment by DartVadius** [comment]
Same issue

**Comment by laurent22** [comment]
Still there

**Comment by yoursinger** [comment]
> 

thank u,your code is work for me!

**Comment by yoursinger** [comment]
> Just to be clear - I am not going to support this package for general usage, so if you decide to use it, be aware of this.

thank u,yours is work for me!
